import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "lt" | "en" | "ru" | "es" | "fr" | "pl" | "de";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  lt: {
    title: "AutoAnalizė",
    subtitle: "pirkimo ir taisymo patarėjas",
    login: "Prisijungti",
    logout: "Atsijungti",
    history: "Istorija",
    analyze: "Analizuoti",
    uploadImages: "Įkelti nuotraukas",
    dropImages: "Nuvilkite nuotraukas čia",
    orClick: "arba spauskite norėdami pasirinkti",
    description: "Aprašymas",
    descriptionPlaceholder: "Įveskite automobilio aprašymą, nuorodą į skelbimą arba bet kokią kitą informaciją...",
    analyzing: "Analizuojama...",
    startAnalysis: "Pradėti analizę",
    marketAnalysis: "Rinkos analizė",
    currentPrice: "Dabartinė kaina",
    marketAverage: "Rinkos vidurkis",
    priceRating: "Kainos įvertinimas",
    repairEstimate: "Remonto sąmata",
    totalCost: "Bendra suma",
    profitability: "Pelningumas",
    resaleValue: "Perpardavimo vertė",
    potentialProfit: "Potencialus pelnas",
    recommendation: "Rekomendacija",
    warnings: "Įspėjimai",
    positives: "Privalumai",
    youtubeVideos: "YouTube vaizdo įrašai",
    noResults: "Nėra rezultatų",
    signUp: "Registruotis",
    signIn: "Prisijungti",
    email: "El. paštas",
    password: "Slaptažodis",
    noAccount: "Neturite paskyros?",
    hasAccount: "Jau turite paskyrą?",
  },
  en: {
    title: "AutoAnalysis",
    subtitle: "purchase and repair advisor",
    login: "Login",
    logout: "Logout",
    history: "History",
    analyze: "Analyze",
    uploadImages: "Upload images",
    dropImages: "Drop images here",
    orClick: "or click to select",
    description: "Description",
    descriptionPlaceholder: "Enter vehicle description, listing URL, or any other information...",
    analyzing: "Analyzing...",
    startAnalysis: "Start analysis",
    marketAnalysis: "Market Analysis",
    currentPrice: "Current Price",
    marketAverage: "Market Average",
    priceRating: "Price Rating",
    repairEstimate: "Repair Estimate",
    totalCost: "Total Cost",
    profitability: "Profitability",
    resaleValue: "Resale Value",
    potentialProfit: "Potential Profit",
    recommendation: "Recommendation",
    warnings: "Warnings",
    positives: "Positives",
    youtubeVideos: "YouTube Videos",
    noResults: "No results",
    signUp: "Sign Up",
    signIn: "Sign In",
    email: "Email",
    password: "Password",
    noAccount: "Don't have an account?",
    hasAccount: "Already have an account?",
  },
  ru: {
    title: "АвтоАнализ",
    subtitle: "советник по покупке и ремонту",
    login: "Войти",
    logout: "Выйти",
    history: "История",
    analyze: "Анализировать",
    uploadImages: "Загрузить фото",
    dropImages: "Перетащите фото сюда",
    orClick: "или нажмите для выбора",
    description: "Описание",
    descriptionPlaceholder: "Введите описание автомобиля, ссылку на объявление или другую информацию...",
    analyzing: "Анализ...",
    startAnalysis: "Начать анализ",
    marketAnalysis: "Анализ рынка",
    currentPrice: "Текущая цена",
    marketAverage: "Средняя по рынку",
    priceRating: "Оценка цены",
    repairEstimate: "Смета ремонта",
    totalCost: "Общая сумма",
    profitability: "Рентабельность",
    resaleValue: "Стоимость перепродажи",
    potentialProfit: "Потенциальная прибыль",
    recommendation: "Рекомендация",
    warnings: "Предупреждения",
    positives: "Преимущества",
    youtubeVideos: "Видео YouTube",
    noResults: "Нет результатов",
    signUp: "Регистрация",
    signIn: "Войти",
    email: "Email",
    password: "Пароль",
    noAccount: "Нет аккаунта?",
    hasAccount: "Уже есть аккаунт?",
  },
  es: {
    title: "AutoAnálisis",
    subtitle: "asesor de compra y reparación",
    login: "Iniciar sesión",
    logout: "Cerrar sesión",
    history: "Historial",
    analyze: "Analizar",
    uploadImages: "Subir imágenes",
    dropImages: "Arrastra las imágenes aquí",
    orClick: "o haz clic para seleccionar",
    description: "Descripción",
    descriptionPlaceholder: "Introduce la descripción del vehículo, enlace del anuncio u otra información...",
    analyzing: "Analizando...",
    startAnalysis: "Iniciar análisis",
    marketAnalysis: "Análisis de mercado",
    currentPrice: "Precio actual",
    marketAverage: "Promedio del mercado",
    priceRating: "Calificación del precio",
    repairEstimate: "Estimación de reparación",
    totalCost: "Costo total",
    profitability: "Rentabilidad",
    resaleValue: "Valor de reventa",
    potentialProfit: "Beneficio potencial",
    recommendation: "Recomendación",
    warnings: "Advertencias",
    positives: "Positivos",
    youtubeVideos: "Videos de YouTube",
    noResults: "Sin resultados",
    signUp: "Registrarse",
    signIn: "Iniciar sesión",
    email: "Correo electrónico",
    password: "Contraseña",
    noAccount: "¿No tienes cuenta?",
    hasAccount: "¿Ya tienes cuenta?",
  },
  fr: {
    title: "AutoAnalyse",
    subtitle: "conseiller achat et réparation",
    login: "Connexion",
    logout: "Déconnexion",
    history: "Historique",
    analyze: "Analyser",
    uploadImages: "Télécharger des images",
    dropImages: "Déposez les images ici",
    orClick: "ou cliquez pour sélectionner",
    description: "Description",
    descriptionPlaceholder: "Entrez la description du véhicule, le lien de l'annonce ou toute autre information...",
    analyzing: "Analyse en cours...",
    startAnalysis: "Démarrer l'analyse",
    marketAnalysis: "Analyse du marché",
    currentPrice: "Prix actuel",
    marketAverage: "Moyenne du marché",
    priceRating: "Évaluation du prix",
    repairEstimate: "Estimation des réparations",
    totalCost: "Coût total",
    profitability: "Rentabilité",
    resaleValue: "Valeur de revente",
    potentialProfit: "Profit potentiel",
    recommendation: "Recommandation",
    warnings: "Avertissements",
    positives: "Points positifs",
    youtubeVideos: "Vidéos YouTube",
    noResults: "Aucun résultat",
    signUp: "S'inscrire",
    signIn: "Se connecter",
    email: "Email",
    password: "Mot de passe",
    noAccount: "Pas de compte?",
    hasAccount: "Déjà un compte?",
  },
  pl: {
    title: "AutoAnaliza",
    subtitle: "doradca zakupu i naprawy",
    login: "Zaloguj się",
    logout: "Wyloguj się",
    history: "Historia",
    analyze: "Analizuj",
    uploadImages: "Prześlij zdjęcia",
    dropImages: "Upuść zdjęcia tutaj",
    orClick: "lub kliknij, aby wybrać",
    description: "Opis",
    descriptionPlaceholder: "Wprowadź opis pojazdu, link do ogłoszenia lub inne informacje...",
    analyzing: "Analizowanie...",
    startAnalysis: "Rozpocznij analizę",
    marketAnalysis: "Analiza rynku",
    currentPrice: "Aktualna cena",
    marketAverage: "Średnia rynkowa",
    priceRating: "Ocena ceny",
    repairEstimate: "Szacunek naprawy",
    totalCost: "Całkowity koszt",
    profitability: "Rentowność",
    resaleValue: "Wartość odsprzedaży",
    potentialProfit: "Potencjalny zysk",
    recommendation: "Rekomendacja",
    warnings: "Ostrzeżenia",
    positives: "Zalety",
    youtubeVideos: "Filmy YouTube",
    noResults: "Brak wyników",
    signUp: "Zarejestruj się",
    signIn: "Zaloguj się",
    email: "Email",
    password: "Hasło",
    noAccount: "Nie masz konta?",
    hasAccount: "Masz już konto?",
  },
  de: {
    title: "AutoAnalyse",
    subtitle: "Kauf- und Reparaturberater",
    login: "Anmelden",
    logout: "Abmelden",
    history: "Verlauf",
    analyze: "Analysieren",
    uploadImages: "Bilder hochladen",
    dropImages: "Bilder hier ablegen",
    orClick: "oder klicken zum Auswählen",
    description: "Beschreibung",
    descriptionPlaceholder: "Fahrzeugbeschreibung, Anzeigenlink oder andere Informationen eingeben...",
    analyzing: "Analysiere...",
    startAnalysis: "Analyse starten",
    marketAnalysis: "Marktanalyse",
    currentPrice: "Aktueller Preis",
    marketAverage: "Marktdurchschnitt",
    priceRating: "Preisbewertung",
    repairEstimate: "Reparaturschätzung",
    totalCost: "Gesamtkosten",
    profitability: "Rentabilität",
    resaleValue: "Wiederverkaufswert",
    potentialProfit: "Potenzieller Gewinn",
    recommendation: "Empfehlung",
    warnings: "Warnungen",
    positives: "Vorteile",
    youtubeVideos: "YouTube-Videos",
    noResults: "Keine Ergebnisse",
    signUp: "Registrieren",
    signIn: "Anmelden",
    email: "E-Mail",
    password: "Passwort",
    noAccount: "Kein Konto?",
    hasAccount: "Bereits ein Konto?",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("language") as Language;
    return saved || "lt";
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
