import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "lt" | "en" | "ru" | "es" | "fr" | "pl" | "de";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  lt: {
    title: "AutoAnalizė",
    subtitle: "pirkimo ir taisymo patarėjas",
    login: "Prisijungti",
    logout: "Atsijungti",
    history: "Istorija",
    analyze: "Analizuoti",
    uploadImages: "Įkelkite nuotraukas",
    dropImages: "Nutempkite arba paspauskite čia",
    imageFormats: "PNG, JPG, WEBP iki 10MB",
    description: "Aprašymas iš skelbimo",
    descriptionPlaceholder: "Įklijuokite skelbimo aprašymą čia...\n\nPvz.: BMW 320d, 2018 m., 150 000 km, dyzelinas, automatinė pavarų dėžė, pilna serviso istorija...",
    listingUrl: "Skelbimo nuoroda (nebūtina)",
    listingUrlPlaceholder: "https://autoplius.lt/...",
    moreInfoBetterAnalysis: "Kuo daugiau informacijos pateiksite, tuo tikslesnė bus analizė",
    analyzing: "Analizuojama su AI...",
    analyzeWithAI: "Analizuoti su AI",
    startAnalysis: "Pradėkite analizę",
    startAnalysisDesc: "Įkelkite nuotraukas ir/arba aprašymą iš skelbimo",
    analysisResults: "Analizės rezultatai",
    marketAnalysis: "Rinkos analizė",
    currentPrice: "Prašoma kaina",
    marketAverage: "Rinkos vidurkis",
    similarVehicles: "panašių automobilių",
    priceRating: "Kainos įvertinimas",
    goodPrice: "Gera kaina",
    averagePrice: "Vidutinė kaina",
    overpriced: "Per brangu",
    repairEstimate: "Remonto sąmata",
    totalRepairCost: "Viso remonto kaina",
    totalCost: "Bendra suma",
    profitability: "Pelningumas",
    resaleValue: "Perpardavimo vertė",
    potentialProfit: "Potencialus pelnas",
    recommendation: "Rekomendacija",
    worthBuying: "Apsimoka pirkti!",
    notRecommended: "Nerekomenduojama pirkti",
    warnings: "Perspėjimai",
    positives: "Privalumai",
    youtubeVideos: "Video instrukcijos remontui",
    noResults: "Nėra rezultatų",
    signUp: "Registruotis",
    signIn: "Prisijungti",
    email: "El. paštas",
    emailPlaceholder: "jusu@pastas.lt",
    password: "Slaptažodis",
    noAccount: "Neturite paskyros?",
    hasAccount: "Jau turite paskyrą?",
    goBack: "Grįžti",
    missingInfo: "Trūksta informacijos",
    uploadOrDescribe: "Įkelkite nuotraukas arba pridėkite aprašymą",
    analysisDone: "Analizė baigta!",
    resultsSaved: "Rezultatai išsaugoti į istoriją",
    loginToSave: "Prisijunkite, kad išsaugotumėte rezultatus",
    error: "Klaida",
    analysisFailed: "Nepavyko atlikti analizės",
    wrongCredentials: "Neteisingas el. paštas arba slaptažodis",
    emailExists: "Šis el. paštas jau užregistruotas",
    successLogin: "Sėkmingai prisijungėte!",
    welcomeBack: "Sveiki sugrįžę",
    accountCreated: "Paskyra sukurta!",
    startUsing: "Galite pradėti naudotis",
    invalidEmail: "Neteisingas el. pašto formatas",
    passwordMin: "Slaptažodis turi būti bent 6 simbolių",
    heroTitle: "analizė ir taisymo patarimai",
    heroHighlight: "AUTO / MOTO",
    heroSubtitle: "Įkelkite skelbimo nuotraukas ir aprašymą – išanalizuosime rinkos kainą, apskaičiuosime remonto kaštus ir parodysime ar apsimoka pirkti. Nusiprikus surasime dalių ir remonto vaizdo medžiagos",
    loginToSaveHistory: "Prisijunkite, kad išsaugotumėte analizių istoriją",
    photoAnalysis: "Nuotraukų analizė",
    photoAnalysisDesc: "AI atpažįsta automobilį, defektus ir bendrą būklę iš nuotraukų",
    marketAnalysisTitle: "Rinkos analizė",
    marketAnalysisDesc: "Realaus laiko kainų palyginimas su panašiais skelbimais",
    profitCalculator: "Pelno skaičiuoklė",
    profitCalculatorDesc: "Sužinokite ar apsimoka pirkti ir perpardavinėti",
    repairEstimateTitle: "Remonto sąmata",
    repairEstimateDesc: "Tikslus remonto kaštų įvertinimas pagal defektus",
    videoInstructions: "Video instrukcijos",
    videoInstructionsDesc: "Suraskite kaip pataisyti konkrečias detales",
    aiRecommendations: "AI rekomendacijos",
    aiRecommendationsDesc: "Išmanios patarimai prieš perkant automobilį",
    vehicle: "Transporto priemonė",
    makeModel: "Markė / Modelis",
    year: "Metai",
    mileage: "Rida",
    fuel: "Kuras",
    transmission: "Pavarų dėžė",
    analysisHistory: "Analizių istorija",
    noSavedAnalyses: "Nėra išsaugotų analizių",
    doFirstAnalysis: "Atlikite pirmą analizę ir ji bus išsaugota čia",
    price: "Kaina",
    deleted: "Ištrinta",
    analysisRemoved: "Analizė pašalinta iš istorijos",
    failedToLoad: "Nepavyko užkrauti istorijos",
    failedToDelete: "Nepavyko ištrinti",
  },
  en: {
    title: "AutoAnalysis",
    subtitle: "purchase and repair advisor",
    login: "Login",
    logout: "Logout",
    history: "History",
    analyze: "Analyze",
    uploadImages: "Upload images",
    dropImages: "Drop or click here",
    imageFormats: "PNG, JPG, WEBP up to 10MB",
    description: "Description from listing",
    descriptionPlaceholder: "Paste the listing description here...\n\nE.g.: BMW 320d, 2018, 150,000 km, diesel, automatic transmission, full service history...",
    listingUrl: "Listing URL (optional)",
    listingUrlPlaceholder: "https://example.com/...",
    moreInfoBetterAnalysis: "The more information you provide, the more accurate the analysis will be",
    analyzing: "Analyzing with AI...",
    analyzeWithAI: "Analyze with AI",
    startAnalysis: "Start analysis",
    startAnalysisDesc: "Upload images and/or description from listing",
    analysisResults: "Analysis results",
    marketAnalysis: "Market Analysis",
    currentPrice: "Asking price",
    marketAverage: "Market Average",
    similarVehicles: "similar vehicles",
    priceRating: "Price Rating",
    goodPrice: "Good price",
    averagePrice: "Average price",
    overpriced: "Overpriced",
    repairEstimate: "Repair Estimate",
    totalRepairCost: "Total repair cost",
    totalCost: "Total Cost",
    profitability: "Profitability",
    resaleValue: "Resale Value",
    potentialProfit: "Potential Profit",
    recommendation: "Recommendation",
    worthBuying: "Worth buying!",
    notRecommended: "Not recommended to buy",
    warnings: "Warnings",
    positives: "Positives",
    youtubeVideos: "Video repair tutorials",
    noResults: "No results",
    signUp: "Sign Up",
    signIn: "Sign In",
    email: "Email",
    emailPlaceholder: "your@email.com",
    password: "Password",
    noAccount: "Don't have an account?",
    hasAccount: "Already have an account?",
    goBack: "Go back",
    missingInfo: "Missing information",
    uploadOrDescribe: "Upload images or add description",
    analysisDone: "Analysis complete!",
    resultsSaved: "Results saved to history",
    loginToSave: "Log in to save results",
    error: "Error",
    analysisFailed: "Analysis failed",
    wrongCredentials: "Wrong email or password",
    emailExists: "This email is already registered",
    successLogin: "Successfully logged in!",
    welcomeBack: "Welcome back",
    accountCreated: "Account created!",
    startUsing: "You can start using the app",
    invalidEmail: "Invalid email format",
    passwordMin: "Password must be at least 6 characters",
    heroTitle: "analysis and repair advice",
    heroHighlight: "AUTO / MOTO",
    heroSubtitle: "Upload listing photos and description – we'll analyze market price, calculate repair costs and show if it's worth buying.",
    loginToSaveHistory: "Log in to save analysis history",
    photoAnalysis: "Photo Analysis",
    photoAnalysisDesc: "AI recognizes the vehicle, defects and overall condition from photos",
    marketAnalysisTitle: "Market Analysis",
    marketAnalysisDesc: "Real-time price comparison with similar listings",
    profitCalculator: "Profit Calculator",
    profitCalculatorDesc: "Find out if it's worth buying and reselling",
    repairEstimateTitle: "Repair Estimate",
    repairEstimateDesc: "Accurate repair cost estimation based on defects",
    videoInstructions: "Video Instructions",
    videoInstructionsDesc: "Find how to fix specific parts",
    aiRecommendations: "AI Recommendations",
    aiRecommendationsDesc: "Smart advice before buying a vehicle",
    vehicle: "Vehicle",
    makeModel: "Make / Model",
    year: "Year",
    mileage: "Mileage",
    fuel: "Fuel",
    transmission: "Transmission",
    analysisHistory: "Analysis History",
    noSavedAnalyses: "No saved analyses",
    doFirstAnalysis: "Complete your first analysis and it will be saved here",
    price: "Price",
    deleted: "Deleted",
    analysisRemoved: "Analysis removed from history",
    failedToLoad: "Failed to load history",
    failedToDelete: "Failed to delete",
  },
  ru: {
    title: "АвтоАнализ",
    subtitle: "советник по покупке и ремонту",
    login: "Войти",
    logout: "Выйти",
    history: "История",
    analyze: "Анализировать",
    uploadImages: "Загрузите фото",
    dropImages: "Перетащите или нажмите сюда",
    imageFormats: "PNG, JPG, WEBP до 10МБ",
    description: "Описание из объявления",
    descriptionPlaceholder: "Вставьте описание объявления сюда...\n\nНапр.: BMW 320d, 2018, 150 000 км, дизель, автомат, полная сервисная история...",
    listingUrl: "Ссылка на объявление (необязательно)",
    listingUrlPlaceholder: "https://example.com/...",
    moreInfoBetterAnalysis: "Чем больше информации вы предоставите, тем точнее будет анализ",
    analyzing: "Анализ с AI...",
    analyzeWithAI: "Анализировать с AI",
    startAnalysis: "Начать анализ",
    startAnalysisDesc: "Загрузите фото и/или описание из объявления",
    analysisResults: "Результаты анализа",
    marketAnalysis: "Анализ рынка",
    currentPrice: "Запрашиваемая цена",
    marketAverage: "Средняя по рынку",
    similarVehicles: "похожих авто",
    priceRating: "Оценка цены",
    goodPrice: "Хорошая цена",
    averagePrice: "Средняя цена",
    overpriced: "Дорого",
    repairEstimate: "Смета ремонта",
    totalRepairCost: "Общая стоимость ремонта",
    totalCost: "Общая сумма",
    profitability: "Рентабельность",
    resaleValue: "Стоимость перепродажи",
    potentialProfit: "Потенциальная прибыль",
    recommendation: "Рекомендация",
    worthBuying: "Стоит покупать!",
    notRecommended: "Не рекомендуется покупать",
    warnings: "Предупреждения",
    positives: "Преимущества",
    youtubeVideos: "Видео инструкции по ремонту",
    noResults: "Нет результатов",
    signUp: "Регистрация",
    signIn: "Войти",
    email: "Email",
    emailPlaceholder: "ваш@email.com",
    password: "Пароль",
    noAccount: "Нет аккаунта?",
    hasAccount: "Уже есть аккаунт?",
    goBack: "Назад",
    missingInfo: "Недостаточно информации",
    uploadOrDescribe: "Загрузите фото или добавьте описание",
    analysisDone: "Анализ завершен!",
    resultsSaved: "Результаты сохранены в историю",
    loginToSave: "Войдите, чтобы сохранить результаты",
    error: "Ошибка",
    analysisFailed: "Не удалось выполнить анализ",
    wrongCredentials: "Неверный email или пароль",
    emailExists: "Этот email уже зарегистрирован",
    successLogin: "Успешный вход!",
    welcomeBack: "С возвращением",
    accountCreated: "Аккаунт создан!",
    startUsing: "Можете начать использование",
    invalidEmail: "Неверный формат email",
    passwordMin: "Пароль должен содержать минимум 6 символов",
    heroTitle: "анализ и советы по ремонту",
    heroHighlight: "АВТО / МОТО",
    heroSubtitle: "Загрузите фото объявления и описание – мы проанализируем рыночную цену, рассчитаем стоимость ремонта и покажем, стоит ли покупать.",
    loginToSaveHistory: "Войдите, чтобы сохранить историю анализов",
    photoAnalysis: "Анализ фото",
    photoAnalysisDesc: "AI распознает автомобиль, дефекты и общее состояние по фото",
    marketAnalysisTitle: "Анализ рынка",
    marketAnalysisDesc: "Сравнение цен в реальном времени с похожими объявлениями",
    profitCalculator: "Калькулятор прибыли",
    profitCalculatorDesc: "Узнайте, стоит ли покупать и перепродавать",
    repairEstimateTitle: "Смета ремонта",
    repairEstimateDesc: "Точная оценка стоимости ремонта по дефектам",
    videoInstructions: "Видео инструкции",
    videoInstructionsDesc: "Найдите как починить конкретные детали",
    aiRecommendations: "AI рекомендации",
    aiRecommendationsDesc: "Умные советы перед покупкой автомобиля",
    vehicle: "Транспортное средство",
    makeModel: "Марка / Модель",
    year: "Год",
    mileage: "Пробег",
    fuel: "Топливо",
    transmission: "Коробка передач",
    analysisHistory: "История анализов",
    noSavedAnalyses: "Нет сохраненных анализов",
    doFirstAnalysis: "Выполните первый анализ, и он будет сохранен здесь",
    price: "Цена",
    deleted: "Удалено",
    analysisRemoved: "Анализ удален из истории",
    failedToLoad: "Не удалось загрузить историю",
    failedToDelete: "Не удалось удалить",
  },
  es: {
    title: "AutoAnálisis",
    subtitle: "asesor de compra y reparación",
    login: "Iniciar sesión",
    logout: "Cerrar sesión",
    history: "Historial",
    analyze: "Analizar",
    uploadImages: "Subir imágenes",
    dropImages: "Arrastra o haz clic aquí",
    imageFormats: "PNG, JPG, WEBP hasta 10MB",
    description: "Descripción del anuncio",
    descriptionPlaceholder: "Pega la descripción del anuncio aquí...\n\nEj.: BMW 320d, 2018, 150.000 km, diésel, transmisión automática, historial de servicio completo...",
    listingUrl: "URL del anuncio (opcional)",
    listingUrlPlaceholder: "https://ejemplo.com/...",
    moreInfoBetterAnalysis: "Cuanta más información proporciones, más preciso será el análisis",
    analyzing: "Analizando con IA...",
    analyzeWithAI: "Analizar con IA",
    startAnalysis: "Iniciar análisis",
    startAnalysisDesc: "Sube imágenes y/o descripción del anuncio",
    analysisResults: "Resultados del análisis",
    marketAnalysis: "Análisis de mercado",
    currentPrice: "Precio solicitado",
    marketAverage: "Promedio del mercado",
    similarVehicles: "vehículos similares",
    priceRating: "Calificación del precio",
    goodPrice: "Buen precio",
    averagePrice: "Precio promedio",
    overpriced: "Sobrevalorado",
    repairEstimate: "Estimación de reparación",
    totalRepairCost: "Costo total de reparación",
    totalCost: "Costo total",
    profitability: "Rentabilidad",
    resaleValue: "Valor de reventa",
    potentialProfit: "Beneficio potencial",
    recommendation: "Recomendación",
    worthBuying: "¡Vale la pena comprar!",
    notRecommended: "No se recomienda comprar",
    warnings: "Advertencias",
    positives: "Positivos",
    youtubeVideos: "Videos tutoriales de reparación",
    noResults: "Sin resultados",
    signUp: "Registrarse",
    signIn: "Iniciar sesión",
    email: "Correo electrónico",
    emailPlaceholder: "tu@correo.com",
    password: "Contraseña",
    noAccount: "¿No tienes cuenta?",
    hasAccount: "¿Ya tienes cuenta?",
    goBack: "Volver",
    missingInfo: "Información faltante",
    uploadOrDescribe: "Sube imágenes o añade descripción",
    analysisDone: "¡Análisis completado!",
    resultsSaved: "Resultados guardados en el historial",
    loginToSave: "Inicia sesión para guardar resultados",
    error: "Error",
    analysisFailed: "Error en el análisis",
    wrongCredentials: "Email o contraseña incorrectos",
    emailExists: "Este email ya está registrado",
    successLogin: "¡Sesión iniciada!",
    welcomeBack: "Bienvenido de nuevo",
    accountCreated: "¡Cuenta creada!",
    startUsing: "Puedes empezar a usar la app",
    invalidEmail: "Formato de email inválido",
    passwordMin: "La contraseña debe tener al menos 6 caracteres",
    heroTitle: "análisis y consejos de reparación",
    heroHighlight: "AUTO / MOTO",
    heroSubtitle: "Sube fotos del anuncio y descripción – analizaremos el precio de mercado, calcularemos costos de reparación y mostraremos si vale la pena comprar.",
    loginToSaveHistory: "Inicia sesión para guardar el historial de análisis",
    photoAnalysis: "Análisis de fotos",
    photoAnalysisDesc: "IA reconoce el vehículo, defectos y estado general desde fotos",
    marketAnalysisTitle: "Análisis de mercado",
    marketAnalysisDesc: "Comparación de precios en tiempo real con anuncios similares",
    profitCalculator: "Calculadora de ganancias",
    profitCalculatorDesc: "Descubre si vale la pena comprar y revender",
    repairEstimateTitle: "Estimación de reparación",
    repairEstimateDesc: "Estimación precisa de costos de reparación según defectos",
    videoInstructions: "Instrucciones en video",
    videoInstructionsDesc: "Encuentra cómo reparar piezas específicas",
    aiRecommendations: "Recomendaciones de IA",
    aiRecommendationsDesc: "Consejos inteligentes antes de comprar un vehículo",
    vehicle: "Vehículo",
    makeModel: "Marca / Modelo",
    year: "Año",
    mileage: "Kilometraje",
    fuel: "Combustible",
    transmission: "Transmisión",
    analysisHistory: "Historial de análisis",
    noSavedAnalyses: "No hay análisis guardados",
    doFirstAnalysis: "Completa tu primer análisis y se guardará aquí",
    price: "Precio",
    deleted: "Eliminado",
    analysisRemoved: "Análisis eliminado del historial",
    failedToLoad: "Error al cargar historial",
    failedToDelete: "Error al eliminar",
  },
  fr: {
    title: "AutoAnalyse",
    subtitle: "conseiller achat et réparation",
    login: "Connexion",
    logout: "Déconnexion",
    history: "Historique",
    analyze: "Analyser",
    uploadImages: "Télécharger des images",
    dropImages: "Déposez ou cliquez ici",
    imageFormats: "PNG, JPG, WEBP jusqu'à 10MB",
    description: "Description de l'annonce",
    descriptionPlaceholder: "Collez la description de l'annonce ici...\n\nEx.: BMW 320d, 2018, 150 000 km, diesel, transmission automatique, historique de service complet...",
    listingUrl: "URL de l'annonce (optionnel)",
    listingUrlPlaceholder: "https://exemple.com/...",
    moreInfoBetterAnalysis: "Plus vous fournissez d'informations, plus l'analyse sera précise",
    analyzing: "Analyse avec IA...",
    analyzeWithAI: "Analyser avec IA",
    startAnalysis: "Démarrer l'analyse",
    startAnalysisDesc: "Téléchargez des images et/ou description de l'annonce",
    analysisResults: "Résultats de l'analyse",
    marketAnalysis: "Analyse du marché",
    currentPrice: "Prix demandé",
    marketAverage: "Moyenne du marché",
    similarVehicles: "véhicules similaires",
    priceRating: "Évaluation du prix",
    goodPrice: "Bon prix",
    averagePrice: "Prix moyen",
    overpriced: "Trop cher",
    repairEstimate: "Estimation des réparations",
    totalRepairCost: "Coût total des réparations",
    totalCost: "Coût total",
    profitability: "Rentabilité",
    resaleValue: "Valeur de revente",
    potentialProfit: "Profit potentiel",
    recommendation: "Recommandation",
    worthBuying: "Ça vaut le coup!",
    notRecommended: "Non recommandé à l'achat",
    warnings: "Avertissements",
    positives: "Points positifs",
    youtubeVideos: "Tutoriels vidéo de réparation",
    noResults: "Aucun résultat",
    signUp: "S'inscrire",
    signIn: "Se connecter",
    email: "Email",
    emailPlaceholder: "votre@email.com",
    password: "Mot de passe",
    noAccount: "Pas de compte?",
    hasAccount: "Déjà un compte?",
    goBack: "Retour",
    missingInfo: "Informations manquantes",
    uploadOrDescribe: "Téléchargez des images ou ajoutez une description",
    analysisDone: "Analyse terminée!",
    resultsSaved: "Résultats sauvegardés dans l'historique",
    loginToSave: "Connectez-vous pour sauvegarder les résultats",
    error: "Erreur",
    analysisFailed: "L'analyse a échoué",
    wrongCredentials: "Email ou mot de passe incorrect",
    emailExists: "Cet email est déjà enregistré",
    successLogin: "Connexion réussie!",
    welcomeBack: "Bon retour",
    accountCreated: "Compte créé!",
    startUsing: "Vous pouvez commencer à utiliser l'app",
    invalidEmail: "Format d'email invalide",
    passwordMin: "Le mot de passe doit contenir au moins 6 caractères",
    heroTitle: "analyse et conseils de réparation",
    heroHighlight: "AUTO / MOTO",
    heroSubtitle: "Téléchargez les photos et la description de l'annonce – nous analyserons le prix du marché, calculerons les coûts de réparation et montrerons si l'achat en vaut la peine.",
    loginToSaveHistory: "Connectez-vous pour sauvegarder l'historique des analyses",
    photoAnalysis: "Analyse photo",
    photoAnalysisDesc: "L'IA reconnaît le véhicule, les défauts et l'état général depuis les photos",
    marketAnalysisTitle: "Analyse du marché",
    marketAnalysisDesc: "Comparaison des prix en temps réel avec des annonces similaires",
    profitCalculator: "Calculateur de profit",
    profitCalculatorDesc: "Découvrez si ça vaut la peine d'acheter et revendre",
    repairEstimateTitle: "Estimation des réparations",
    repairEstimateDesc: "Estimation précise des coûts de réparation selon les défauts",
    videoInstructions: "Instructions vidéo",
    videoInstructionsDesc: "Trouvez comment réparer des pièces spécifiques",
    aiRecommendations: "Recommandations IA",
    aiRecommendationsDesc: "Conseils intelligents avant d'acheter un véhicule",
    vehicle: "Véhicule",
    makeModel: "Marque / Modèle",
    year: "Année",
    mileage: "Kilométrage",
    fuel: "Carburant",
    transmission: "Transmission",
    analysisHistory: "Historique des analyses",
    noSavedAnalyses: "Aucune analyse sauvegardée",
    doFirstAnalysis: "Effectuez votre première analyse et elle sera sauvegardée ici",
    price: "Prix",
    deleted: "Supprimé",
    analysisRemoved: "Analyse supprimée de l'historique",
    failedToLoad: "Échec du chargement de l'historique",
    failedToDelete: "Échec de la suppression",
  },
  pl: {
    title: "AutoAnaliza",
    subtitle: "doradca zakupu i naprawy",
    login: "Zaloguj się",
    logout: "Wyloguj się",
    history: "Historia",
    analyze: "Analizuj",
    uploadImages: "Prześlij zdjęcia",
    dropImages: "Upuść lub kliknij tutaj",
    imageFormats: "PNG, JPG, WEBP do 10MB",
    description: "Opis z ogłoszenia",
    descriptionPlaceholder: "Wklej opis ogłoszenia tutaj...\n\nNp.: BMW 320d, 2018, 150 000 km, diesel, automatyczna skrzynia biegów, pełna historia serwisowa...",
    listingUrl: "Link do ogłoszenia (opcjonalnie)",
    listingUrlPlaceholder: "https://przyklad.pl/...",
    moreInfoBetterAnalysis: "Im więcej informacji podasz, tym dokładniejsza będzie analiza",
    analyzing: "Analiza z AI...",
    analyzeWithAI: "Analizuj z AI",
    startAnalysis: "Rozpocznij analizę",
    startAnalysisDesc: "Prześlij zdjęcia i/lub opis z ogłoszenia",
    analysisResults: "Wyniki analizy",
    marketAnalysis: "Analiza rynku",
    currentPrice: "Cena wywoławcza",
    marketAverage: "Średnia rynkowa",
    similarVehicles: "podobnych pojazdów",
    priceRating: "Ocena ceny",
    goodPrice: "Dobra cena",
    averagePrice: "Średnia cena",
    overpriced: "Za drogo",
    repairEstimate: "Szacunek naprawy",
    totalRepairCost: "Całkowity koszt naprawy",
    totalCost: "Całkowity koszt",
    profitability: "Rentowność",
    resaleValue: "Wartość odsprzedaży",
    potentialProfit: "Potencjalny zysk",
    recommendation: "Rekomendacja",
    worthBuying: "Warto kupić!",
    notRecommended: "Nie zaleca się kupowania",
    warnings: "Ostrzeżenia",
    positives: "Zalety",
    youtubeVideos: "Filmy instruktażowe naprawy",
    noResults: "Brak wyników",
    signUp: "Zarejestruj się",
    signIn: "Zaloguj się",
    email: "Email",
    emailPlaceholder: "twoj@email.pl",
    password: "Hasło",
    noAccount: "Nie masz konta?",
    hasAccount: "Masz już konto?",
    goBack: "Wróć",
    missingInfo: "Brakujące informacje",
    uploadOrDescribe: "Prześlij zdjęcia lub dodaj opis",
    analysisDone: "Analiza zakończona!",
    resultsSaved: "Wyniki zapisane do historii",
    loginToSave: "Zaloguj się, aby zapisać wyniki",
    error: "Błąd",
    analysisFailed: "Analiza nie powiodła się",
    wrongCredentials: "Nieprawidłowy email lub hasło",
    emailExists: "Ten email jest już zarejestrowany",
    successLogin: "Zalogowano pomyślnie!",
    welcomeBack: "Witaj ponownie",
    accountCreated: "Konto utworzone!",
    startUsing: "Możesz zacząć korzystać z aplikacji",
    invalidEmail: "Nieprawidłowy format email",
    passwordMin: "Hasło musi mieć co najmniej 6 znaków",
    heroTitle: "analiza i porady naprawcze",
    heroHighlight: "AUTO / MOTO",
    heroSubtitle: "Prześlij zdjęcia ogłoszenia i opis – przeanalizujemy cenę rynkową, obliczymy koszty naprawy i pokażemy, czy warto kupić.",
    loginToSaveHistory: "Zaloguj się, aby zapisać historię analiz",
    photoAnalysis: "Analiza zdjęć",
    photoAnalysisDesc: "AI rozpoznaje pojazd, wady i ogólny stan ze zdjęć",
    marketAnalysisTitle: "Analiza rynku",
    marketAnalysisDesc: "Porównanie cen w czasie rzeczywistym z podobnymi ogłoszeniami",
    profitCalculator: "Kalkulator zysku",
    profitCalculatorDesc: "Dowiedz się, czy warto kupić i odsprzedać",
    repairEstimateTitle: "Szacunek naprawy",
    repairEstimateDesc: "Dokładna wycena kosztów naprawy na podstawie wad",
    videoInstructions: "Instrukcje wideo",
    videoInstructionsDesc: "Znajdź jak naprawić konkretne części",
    aiRecommendations: "Rekomendacje AI",
    aiRecommendationsDesc: "Inteligentne porady przed zakupem pojazdu",
    vehicle: "Pojazd",
    makeModel: "Marka / Model",
    year: "Rok",
    mileage: "Przebieg",
    fuel: "Paliwo",
    transmission: "Skrzynia biegów",
    analysisHistory: "Historia analiz",
    noSavedAnalyses: "Brak zapisanych analiz",
    doFirstAnalysis: "Wykonaj pierwszą analizę, a zostanie tutaj zapisana",
    price: "Cena",
    deleted: "Usunięto",
    analysisRemoved: "Analiza usunięta z historii",
    failedToLoad: "Nie udało się załadować historii",
    failedToDelete: "Nie udało się usunąć",
  },
  de: {
    title: "AutoAnalyse",
    subtitle: "Kauf- und Reparaturberater",
    login: "Anmelden",
    logout: "Abmelden",
    history: "Verlauf",
    analyze: "Analysieren",
    uploadImages: "Bilder hochladen",
    dropImages: "Ablegen oder hier klicken",
    imageFormats: "PNG, JPG, WEBP bis 10MB",
    description: "Beschreibung aus Anzeige",
    descriptionPlaceholder: "Fügen Sie die Anzeigenbeschreibung hier ein...\n\nZ.B.: BMW 320d, 2018, 150.000 km, Diesel, Automatik, vollständige Servicehistorie...",
    listingUrl: "Anzeigen-URL (optional)",
    listingUrlPlaceholder: "https://beispiel.de/...",
    moreInfoBetterAnalysis: "Je mehr Informationen Sie angeben, desto genauer wird die Analyse",
    analyzing: "Analyse mit KI...",
    analyzeWithAI: "Mit KI analysieren",
    startAnalysis: "Analyse starten",
    startAnalysisDesc: "Laden Sie Bilder und/oder Beschreibung aus der Anzeige hoch",
    analysisResults: "Analyseergebnisse",
    marketAnalysis: "Marktanalyse",
    currentPrice: "Angebotspreis",
    marketAverage: "Marktdurchschnitt",
    similarVehicles: "ähnliche Fahrzeuge",
    priceRating: "Preisbewertung",
    goodPrice: "Guter Preis",
    averagePrice: "Durchschnittlicher Preis",
    overpriced: "Zu teuer",
    repairEstimate: "Reparaturschätzung",
    totalRepairCost: "Gesamte Reparaturkosten",
    totalCost: "Gesamtkosten",
    profitability: "Rentabilität",
    resaleValue: "Wiederverkaufswert",
    potentialProfit: "Potenzieller Gewinn",
    recommendation: "Empfehlung",
    worthBuying: "Lohnt sich zu kaufen!",
    notRecommended: "Kauf nicht empfohlen",
    warnings: "Warnungen",
    positives: "Vorteile",
    youtubeVideos: "Video-Reparaturanleitungen",
    noResults: "Keine Ergebnisse",
    signUp: "Registrieren",
    signIn: "Anmelden",
    email: "E-Mail",
    emailPlaceholder: "ihre@email.de",
    password: "Passwort",
    noAccount: "Kein Konto?",
    hasAccount: "Bereits ein Konto?",
    goBack: "Zurück",
    missingInfo: "Fehlende Informationen",
    uploadOrDescribe: "Laden Sie Bilder hoch oder fügen Sie eine Beschreibung hinzu",
    analysisDone: "Analyse abgeschlossen!",
    resultsSaved: "Ergebnisse im Verlauf gespeichert",
    loginToSave: "Melden Sie sich an, um Ergebnisse zu speichern",
    error: "Fehler",
    analysisFailed: "Analyse fehlgeschlagen",
    wrongCredentials: "Falsche E-Mail oder Passwort",
    emailExists: "Diese E-Mail ist bereits registriert",
    successLogin: "Erfolgreich angemeldet!",
    welcomeBack: "Willkommen zurück",
    accountCreated: "Konto erstellt!",
    startUsing: "Sie können die App jetzt nutzen",
    invalidEmail: "Ungültiges E-Mail-Format",
    passwordMin: "Passwort muss mindestens 6 Zeichen haben",
    heroTitle: "Analyse und Reparaturberatung",
    heroHighlight: "AUTO / MOTO",
    heroSubtitle: "Laden Sie Anzeigenfotos und Beschreibung hoch – wir analysieren den Marktpreis, berechnen Reparaturkosten und zeigen, ob sich der Kauf lohnt.",
    loginToSaveHistory: "Melden Sie sich an, um den Analyseverlauf zu speichern",
    photoAnalysis: "Fotoanalyse",
    photoAnalysisDesc: "KI erkennt das Fahrzeug, Mängel und den Gesamtzustand aus Fotos",
    marketAnalysisTitle: "Marktanalyse",
    marketAnalysisDesc: "Echtzeit-Preisvergleich mit ähnlichen Anzeigen",
    profitCalculator: "Gewinnrechner",
    profitCalculatorDesc: "Erfahren Sie, ob sich Kauf und Weiterverkauf lohnen",
    repairEstimateTitle: "Reparaturschätzung",
    repairEstimateDesc: "Genaue Reparaturkostenschätzung basierend auf Mängeln",
    videoInstructions: "Video-Anleitungen",
    videoInstructionsDesc: "Finden Sie, wie Sie bestimmte Teile reparieren",
    aiRecommendations: "KI-Empfehlungen",
    aiRecommendationsDesc: "Intelligente Ratschläge vor dem Fahrzeugkauf",
    vehicle: "Fahrzeug",
    makeModel: "Marke / Modell",
    year: "Jahr",
    mileage: "Kilometerstand",
    fuel: "Kraftstoff",
    transmission: "Getriebe",
    analysisHistory: "Analyseverlauf",
    noSavedAnalyses: "Keine gespeicherten Analysen",
    doFirstAnalysis: "Führen Sie Ihre erste Analyse durch und sie wird hier gespeichert",
    price: "Preis",
    deleted: "Gelöscht",
    analysisRemoved: "Analyse aus dem Verlauf entfernt",
    failedToLoad: "Verlauf konnte nicht geladen werden",
    failedToDelete: "Löschen fehlgeschlagen",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("language") as Language;
    return saved || "lt";
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
